### ISSUE TITLE
Add ability to select columns along with reordering

### ISSUE THREAD

**Issue by morgan** [caxiam/ember-tabular#85] opened 2017-06-22 21:34 UTC
- [x] Call to action that presents user with a panel
- [x] Panel has a list of the available columns with a checkbox next to the name
- [x] List should be reorderable

**Comment by aaronfischer** [comment] 2017-06-23 04:32
@morgan I have some ideas on how I could setup the columns/option based on the model.

But when it comes to the cell templates. I'm not sure how we'd give the user the ability to customize what can go inside the cells if the columns are dynamic generated.

The only thing I can think of at the moment is to setup a template for each and every one of the model's attributes, that way when the user chooses different columns we have a template that is matched up.
e.g. So by default only 3 columns are shown, but the model has 7 attributes total, when the table is setup there would be 7 templates defined based on these attributes then the user can choose more/less columns and then we'd have a template already defined for each of the possible attributes/columns.

I'm going to continue to think over this, but if you had any first thoughts I'd be interested to hear.

**Comment by morgan** [comment] 2017-06-23 05:01
Perhaps a component defining/wrapping each cell in a single template? As the rows are iterated, the cell component could conditionally check for visibility. 

Certainly do not want to render the cell unless the cell is chosen. If only 5 columns are chosen of let's say 15, do not want the overhead of processing each cell that is hidden.

**Comment by aaronfischer** [comment] 2017-06-26 18:37
@morgan I'm a bit stuck, so I have the component setup to iterate each row, then iterate each column, within that iteration I'm checking if the column.isActive, if it is then I run it through the ember-tabular-cell component which will output the specific data based on the record's attribute.

However, I'm stuck because I want it to always render the ember-tabular-cell, regardless if a block or inline form is used. I want the component(s) to be smart enough to not render the inline version if the block-form is used but I haven't figured out a way of doing that. (Right now I have this un-used "column.isCustom" attribute, but we wont always have access to the column, I was hoping there was a way of detecting that within the template)

```hbs
<!-- ember-tabular -->
...
{{#if record}}
    {{#each record as |row|}}
        {{partial trRow}}
    {{/each}}
{{else}}
...
```

```hbs
<!-- row template -->
<tr>
  {{#each columns as |column|}}
    {{#if column.isActive}}
      {{!-- TODO: must be a way to use yield or inline form based on a property --}}
      {{#if column.isCustom}}
        {{yield (hash
          cell=(component "ember-tabular-cell" column=column record=row colProperty=colProperty)
        )}}
      {{else}}
        {{ember-tabular-cell column=column record=row colProperty=column.property}}
      {{/if}}
    {{/if}}
  {{/each}}
</tr>
```

**Comment by aaronfischer** [comment] 2017-06-27 07:09
@morgan Hmm, Okay so based on our recent conversation here is what I've discovered so far.

If we try to build/construct the `columns` based on the yielded objects in the handlebars template, something like:
```hbs
{{#ember-tabular modelName="user" as |section|}}
    {{#section.cell colProperty="emailAddress" as |record column|}}
        <a href="mailto:{{get record column.property}}">{{get record column.property}}</a>
    {{/section.cell}}
    {{#section.cell colProperty="updatedAt" as |record column|}}
        {{moment-format (get record column.property) 'MM/DD/YYYY'}}
    {{/section.cell}}
{{/ember-tabular}}
```
Where these 2 yielded section `cell`s are custom templates and their `colProperty` would be added to the initial `columns` within their `init()` hook. Then once ember-tabular is initialized it would then check these and generate the remaining `columns` based off the model.
This is essentially the format/functionality we were discussing right?

The issue is the order in which things are initialized, ember-tabular comes before the cell component which screws up what is required when ember-tabular is initialized. 

Unless I can think of a different way to set this up I think we may want to stick with a config array, where the user defines an array of objects, with a primary `property` key, along with a few other options like `isCustomTemplate`, etc, this could possibly be merged with the `columns` array or it could be a config outside of it, I'm not sure on that detail yet. 
Either way, this config would allow us to perform a lookup when iterating the `columns` array and based on something like `isCustomTemplate` it would look for `{{#section.cell ...}}`(in block form) override like the example above. If `isCustomTemplate` was false or doesn't exist then just use the default template within the `cell` component.

**Comment by morgan** [comment] 2017-06-27 07:23
Is the concern only around the order of the columns? There are likely multiple ways to decouple the initialization of the columns with the actual rendering of the ordered values.

**Comment by aaronfischer** [comment] 2017-06-27 15:57
@morgan Nope, I've actually solved that by looping through the `columns` array when rendering the table header and table body/cells. This keeps them independent from whatever order the user may put them in when setting up the handlebars/initializing ember-tabular on the page.

The real issue is that there is no way of knowing the contents of a yield within the outer scope. Really there is no way of knowing the contents of a yield period, you can only perform some work within the yielded component's initializer, but that can be pretty taxing... if you have 100 or even 1000 cells your trying to perform work adding that unique/new column to the `columns` array.

I'm thinking we have to go the config way, there needs to be some kind of config setup before the components are yielded so that when it is looped and initialized it knows what to do immediately because the config is already complete, its not being built on the fly.

Another benefit of the config is that we would use this to setup the default columns to be displayed, by default all would be displayed unless the config says otherwise.

**Comment by morgan** [comment] 2017-06-27 17:14
@Aaronfischer So, your brick wall is around knowing what columns where explicitly defined?

**Comment by aaronfischer** [comment] 2017-06-27 18:22
@morgan Right, I don't see there being a way to know what was defined if they're only defined within ember-tabular's `yield` and no-where else.

**Comment by morgan** [comment] 2017-06-27 18:35
Cool. I'll give you a call and we'll work through it.

**Comment by aaronfischer** [comment] 2017-06-27 18:42
@morgan 👍

**Comment by aaronfischer** [comment] 2017-06-28 19:25
@morgan This is the current setup:

User defines an ember-tabular table in a "hybrid" fashion
```hbs
{{#ember-tabular modelName="user" sort=sort as |et|}}
    {{#et.column property="emailAddress" isCustom=true as |record column|}}
        <a href="mailto:{{get record column.property}}">{{get record column.property}}</a>
    {{/et.column}}
    {{#et.column property="updatedAt" isCustom=true as |record column|}}
        {{moment-format (get record column.property) 'MM/DD/YYYY'}}
    {{/et.column}}
    {{#et.column
        property="actions"
        isCustom=true
        filter=false
        sort=false
    }}
        {{#link-to "index" class="btn btn-default btn-xs" role="button"}}
            Edit
        {{/link-to}}
    {{/et.column}}
{{/ember-tabular}}
```
In the above example, `emailAddress`, `updatedAt`, and `actions` create objects and are added to a `registry` array that is set on `ember-tabular`. Then, once these yielded `ember-tabular-column` components are finished thats where we loop over and create the remaining column objects via an array `registryDiff`, which are then combined into `columns` which is what the templates use to render the thead/tbody-rows.
(The only way to detect that they are completely yielded is via `ember-tabular-footer` which fires an action on its init up to `ember-tabular` that the registry is complete and we can now proceed.)

```js
// components/ember-tabular.js
...
  columns: Ember.computed('registry', 'registryDiff', 'registryDone', 'columnOrder', function () {
    const columns = Ember.A();
    // only output columns array when registry is done
    if (this.get('registryDone')) {
      const registry = this.get('registry');
      const registryDiff = this.get('registryDiff');
      const columnOrder = this.get('columnOrder');

      if (registry && registryDiff) {
        columns.pushObjects(registry);
        columns.pushObjects(registryDiff);
      }

      // sort the colums array by columnOrder
      if (columnOrder) {
        columns.sort((a, b) => columnOrder.indexOf(a.property) < columnOrder.indexOf(b.property) ? -1 : 1);
      }
    }
    return columns;
  }),

  registryDone: false,

  // Ember.A() to be defined in init()
  registry: null,

  registryDiff: Ember.computed('registry.[]', function () {
    const modelName = this.get('modelName');
    const registry = this.get('registry');
    let registryDiff = Ember.A();
    if (modelName) {
      const modelClass = this.get('store').modelFor(modelName);
      const modelClassAttributes = Ember.get(modelClass, 'attributes');
      // iterate over keys and create attribute array
      modelClassAttributes.forEach((meta, property) => {
        let attribute = {
          property: property,
          label: this._formatColumnLabel(property),
          isActive: true,
          isCustomTemplate: false,
          filter: true,
          sort: true,
          type: 'text',
        };
        // look for duplicate
        let item = registry.find((el) => {
          return el.property === property;
        });
        if (!item) {
          registryDiff.addObject(attribute);
        }
      });
    }
    return registryDiff;
  }),
...
```

* There are also other options to override the `columns` property if the user wants to be explicit.
* When `ember-tabular-column` is defined all of the column object properties can be passed so that they are setup on the column object and added into the `registry`.
* If the `columns` are automatically generated (or a hybrid) and the columns need to be in a specific order, you can pass a simple array: `columnOrder: [... 'lastName', 'isAdmin', 'createdAt', 'updatedAt', 'actions' ];` and they're be re-ordered.

Still to do:
* Setup a way to reorder the columns in the interface, I'm thinking I can setup/modify `orderConfig` via the `ember-tabular-column-select` component. (This is what powers the column select popup panel)
* Fix and add additional testing coverage.

**Comment by morgan** [comment] 2017-06-28 19:33
I thought this was impossible? ;)

**Comment by aaronfischer** [comment] 2017-06-28 19:38
@morgan Hahah! I never meant to say  "impossible" 😝 I just didn't see a clear path, I'd really like to figure out how to remove the `ember-tabular-footer` but I don't know of another way to detect when block yields are all initialized.
(I definitely ran into some major head scratchers along the way though, I was still thinking very improbable until about 3-4am last night)

**Closed as completed** 2017-07-06 04:38 UTC
Labels: enhancement
